### ISSUE TITLE
tut4 events

### ISSUE THREAD

**Issue by michaelworcester** [ShabbyX/vktut#1]
Events cannot be used between queues, they are fine grained synchronisation for the _same_ queue. They can be used (with limitations) between the device and the host.

**Comment by ShabbyX** [comment]
@michaelworcester Thanks for taking the time to verify my comments, I really appreciate it.

You are right, I reread the specification and reworded my comment here: ae658613e1817a95fd07a2590b5c5f4c227ad078

Other than synchronization with host, I find it hard to imagine what advantage events might have over pipeline barriers. First, what limitations are you talking about? And second, if you have more information on this subject, I would be glad to hear and learn.

**Comment by michaelworcester** [comment]
Events can be used across command buffers, pipeline barriers only provide execution dependency within a command buffer.

The limitations of setting an event on the host after already submitting a command that is waiting on that event. You have a limited time (implementation dependent) before the implementation may decide your command has timed out and may give you a device lost (or something similar).

**Comment by ShabbyX** [comment]
Thanks for clearing that up!
