### ISSUE TITLE
Complete build options for Pthread API

### ISSUE THREAD

**Issue by elfring** [ShabbyX/vktut#3]
Would you like to add the configuration script "[AX_PTHREAD](https://www.gnu.org/software/autoconf-archive/ax_pthread.html)" to [your build specification](https://github.com/ShabbyX/vktut/blob/b12acfd1e7b4c61286af4a016bd414c90c5c3abe/configure.ac#L30)?

**Comment by ShabbyX** [comment]
Yes, yes I would.
