### ISSUE TITLE
Completion of error handling

### ISSUE THREAD

**Issue by elfring** [ShabbyX/vktut#4]
Would you like to [add more error handling](https://github.com/ShabbyX/vktut/blob/3a0f044109b0eab1b6c616e41a7ea4031ca2e16d/tut4/tut4.c#L190) for return values from the call of a function like "[pthread_mutex_init](http://pubs.opengroup.org/onlinepubs/9699919799/functions/pthread_mutex_init.html)"?

**Comment by elfring** [comment]
Thanks for [your small source code improvement](https://github.com/ShabbyX/vktut/commit/48847a7ac709fc638df4b3a859ebe436f9bf0e12).
Are there [a few update candidates left over](https://github.com/ShabbyX/vktut/blob/48847a7ac709fc638df4b3a859ebe436f9bf0e12/tut4/tut4.c#L395)?

**Comment by ShabbyX** [comment]
Did you see [the commit that followed immediately after](https://github.com/ShabbyX/vktut/commit/b7a3246cea5034abc89e6ccfc3ca4ff6683d61bf)?

**Comment by elfring** [comment]
Thanks for [another small source code improvement](https://github.com/ShabbyX/vktut/commit/b7a3246cea5034abc89e6ccfc3ca4ff6683d61bf).

**Comment by ShabbyX** [comment]
I'm confused, is this sarcasm?

**Comment by elfring** [comment]
I hope not.

**Comment by ShabbyX** [comment]
Thanks, I thought you are saying "there are a lot of errors, and you just made a very small change".

Moving on...

**Comment by elfring** [comment]
Your software is also becoming better step by step as usual, isn't it?

**Comment by ShabbyX** [comment]
Yes, and thank you for that

**Comment by elfring** [comment]
Are you interested to apply [aspect-oriented software development](http://aspectc.org/)?
How do you think about to encapsulate error detection and corresponding exception handling as [a reusable aspect](https://en.wikipedia.org/wiki/Aspect_%28computer_programming%29) in your software?

**Comment by ShabbyX** [comment]
I had actually been thinking about doing something like that (didn't know it had a name). In particular, having a proper error report mechanism that doesn't get in the way of the tutorials itself would have resulted in a better output than in #5, or wouldn't have forced me to report an unrelated Vulkan error code when a POSIX mutex fails.

I'll be adding this sometime soon.
