### ISSUE TITLE
tut8 error

### ISSUE THREAD

**Issue by barotto** [ShabbyX/vktut#5]
I've got this error in tut8:

```
Could not create graphics pipeline: Incomplete
Segmentation fault (core dumped)
```

All other tuts are working fine.
My system: Ubuntu 14.04, GeForce GTX 970, driver version 367.27

**Comment by barotto** [comment]
The segmentation fault is caused in tut8_free_pipelines() by passing a NULL pipelines[i].pipeline to vkDestroyPipeline()

**Comment by michaelworcester** [comment]
Is this segfaulting in the app or the driver?

NULL handles are generally safe to pass to vkDestroy\* functions, in which case the function won't do anything.

https://www.khronos.org/registry/vulkan/specs/1.0/xhtml/vkspec.html#pipelines-destruction

> If pipeline is not VK_NULL_HANDLE, pipeline must be a valid VkPipeline handle

**Comment by barotto** [comment]
It appears to segfault in the driver.
This is the call stack:

```
Thread [1] 20908 [core: 4] (Suspended : Signal : SIGSEGV:Segmentation fault)    
    0x7ffff10b3d2b  
    0x7ffff10b4139  
    tut8_free_pipelines() at /home/marco/workspace/vktut-barotto/tut8/tut8.c:474 0x4034ba   
    free_render_data() at /home/marco/workspace/vktut-barotto/tut8/main.c:383 0x40407f  
    render_loop() at /home/marco/workspace/vktut-barotto/tut8/main.c:548 0x404411   
    main() at /home/marco/workspace/vktut-barotto/tut8/main.c:638 0x40474e  
```

**Comment by ShabbyX** [comment]
First, the segmentation fault is a bug in the nvidia driver. I have already reported this to nvidia, but feel free to report it yourself as well.

You can see a brief discussion regarding this (as well as a similar bug in a validation layer) here: https://github.com/LunarG/VulkanTools/issues/60

**Comment by ShabbyX** [comment]
Regarding your actual issue, I admit that the error reporting could have been more complete, but that would have probably made the tutorials even harder to read.

That said, you could try debugging the issue by either:
1. Putting logs in `tut7_create_graphics_buffers` to see what fails
2. Using gdb to see what fails

I actually have the same card and driver as you. Are you on x86_64? What version of Vulkan do you have installed?

**Comment by barotto** [comment]
I used gdb to take single steps through the code. 
It fails at tut8.c:464, the vkCreateGraphicsPipelines returns VK_ERROR_INVALID_SHADER_NV
I'm on x86_64 and vulkaninfo returns API Version 1.0.8
I downloaded the glslangValidator binary from khronos.org, revision 33062.
According to the nvidia docs I should use the VK_EXT_debug_report extension to get more details.

**Comment by ShabbyX** [comment]
Perhaps this is an issue with `glslangValidator` and Vulkan versions. I have Vulkan 1.0.17 installed from the LunarG downloaded package (the installation was a bit of manual work but not too difficult), which includes `glslangValidator`:

```
$ glslangValidator -v
Glslang Version: SPIRV99.947 15-Feb-2016
ESSL Version: OpenGL ES GLSL 3.00 glslang LunarG Khronos.SPIRV99.947 15-Feb-2016
GLSL Version: 4.20 glslang LunarG Khronos.SPIRV99.947 15-Feb-2016
SPIR-V Version 0x00010000, Revision 3
GLSL.std.450 Version 100, Revision 1
Khronos Tool ID 8
```

Would you be willing to update your Vulkan SDK installation and see what happens?

**Comment by barotto** [comment]
Alright, I replaced the glslangValidator downloaded from khronos.org with the version included in the VulkanSDK package from LunarG, keeping the vulkan lib to version 1.0.8. 
Now tut8 works.
The glslangValidator binary from the Khronos site is actually quite old:

```
$ glslangValidator -v
Glslang Version: 3.0.780 06-Oct-2015
ESSL Version: OpenGL ES GLSL 3.00 glslang LunarG Khronos.3.0.780 06-Oct-2015
GLSL Version: 4.20 glslang LunarG Khronos.3.0.780 06-Oct-2015
SPIR-V Version 99, Revision 31
GLSL.std.450 Version 99, Revision 2
```

**Comment by ShabbyX** [comment]
Oh, I'm surprised that what you downloaded had been actually older! Anyway, have fun :)
